name: tests
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: test
      run: |
        export GO111MODULE=on
        export TZ="America/Chicago"
        export MONGO_TEST=mongodb://127.0.0.1:27017
        go test ./... -bench=.
          

    - name: install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.23.3

    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./...

